dirs:
  - ./docs
  - ./versioned_docs
excludedDirs:
  - ./build
  - ./.vercel
  - ./.docusaurus
  - ./node_modules
useGitIgnore: true

ignorePatterns:
- pattern: '^http(s)?://localhost'
- pattern: '^http(s)?://127.0.0.1'
- pattern: '^http(s)?://gitlab.com/ConsenSys/'
- pattern: '^http(s)?://consensys.net'
- pattern: '^http(s)?://.+.zendesk.com'
- pattern: '^http(s)?://.+.etherscan.io'
- pattern: '^http(s)?://help.figma.com'
- pattern: '^http(s)?://metamask.io'
aliveStatusCodes:
- 200
- 206
- 400
- 403
timeout: 30
maxRetries: 2
maxResponseBodySize: 10485760