dirs:
  - ./docs
excludedDirs:
  - ./build
  - ./.vercel
  - ./.docusaurus
  - ./node_modules
  - ./versioned_docs
useGitIgnore: true
followRedirects: true

ignorePatterns:
- pattern: '^http(s)?://localhost'
- pattern: '^http(s)?://127.0.0.1'
- pattern: '^http(s)?://gitlab.com/ConsenSys/'
- pattern: '^http(s)?://consensys.net'
- pattern: '^http(s)?://.+.zendesk.com'
- pattern: '^http(s)?://.+.etherscan.io'
- pattern: '^http(s)?://help.figma.com'
- pattern: '^http(s)?://metamask.io'
- pattern: '^http(s)?://(www\.)?freedesktop\.org'
aliveStatusCodes:
- 200
- 206
- 400
- 403