/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "Tutorials" }],
  // apiSidebar: [
  //   {
  //     type: "category",
  //     label: "Teku",
  //     link: {
  //       type: "generated-index",
  //       title: "Teku API",
  //       slug: "/category/teku-api",
  //     },
  //     //@ts-ignore
  //     items: require("./docs/api-gen/sidebar.js"),
  //   },
  // ],
  docSidebar: [
    "index",
    {
      type: "category",
      label: "How to",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "HowTo" }],
    },
    {
      type: "category",
      label: "Concepts",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "Concepts" }],
    },
    {
      type: "category",
      label: "Tutorials",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "Tutorials" }],
    },
  ],
  referenceSidebar: [
    {
      type: "category",
      label: "Teku command line",
      items: [{ type: "autogenerated", dirName: "Reference/CLI" }],
    },
    "Reference/Rest_API/Rest",
  ],
};

module.exports = sidebars;
