name: Fix Content
description: Report issues with the documentation content
labels: ['update']
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to submit this issue. Your input is appreciated.
  - type: textarea
    id: issue-location
    attributes:
      label: Where is the issue?
      description: Link to the documentation page(s) where you identified this issue.
      placeholder: 
  - type: checkboxes
    id: issue-type
    attributes:
      label: Issue type
      description: Select the type(s) of issue you are reporting.
      options:
        - label: Missing content
          required: false
        - label: Outdated content
          required: false
        - label: Inaccurate information
          required: false
  - type: textarea
    id: issue-description
    attributes:
      label: Detailed issue description
      description: Describe the issue in more detail.
      placeholder: What needs to change?
      required: true
  - type: textarea
    id: text-resolution
    attributes:
      label: What should be in the docs?
      description: Provide a suggested resolution if available.
      placeholder:
  - type: textarea
    id: information
    attributes:
      label: Additional information
      description: Add any other context about the problem here.
      placeholder: Leave this section blank if it does not apply.
