name: New Content
description: Suggest new content or a report documentation needed for a new feature.
labels: ['new-content']
body:
  - type: textarea
    id: issue-description
    attributes:
      label: Description
      description: Provide a detailed description of the content suggestion or new feature documentation, including any context.
      placeholder:
    validations:
      required: true
  - type: textarea
    id: issue-location
    attributes:
      label: Where should this content be added?
      description: Link to or describe the documentation section(s) where this new content should be added.
      placeholder:
