name: Site
description: Request updates to the documentation site that impact its user interface or functionality.
labels: ['site']
body:
  - type: checkboxes
    id: issue-type
    attributes:
      label: Site issue type
      description: Select the type(s) of issue you are reporting.
      options:
        - label: Configuration and plugins
          description: Issues related to Docusaurus configuration or plugins
          required: false
        - label: UI/UX
          description: Issues related to the look and feel or user experience of the site.
          required: false
        - label: Site infrastructure
          description: Issues related to backend site infrastructure.
          required: false
        - label: Other
          description: Issues related to other site functionality or appearance.
          required: false
- type: textarea
    id: issue-description
    attributes:
      label: Description
      description: Provide a detailed description of the issue, including any context.
      placeholder: 
    validations:
      required: true
- type: textarea
    id: suggested-change
    attributes:
      label: How should this issue be addressed?
      description: Provide a suggested change if available.
      placeholder: Leave blank if this does not apply.
