---
name: Build

on:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Build
        uses: ConsenSys/github-actions/docs-build@60d442d6d385b414c8e00eb049a85f56f9fd7be7 # main
