---
name: Build

on:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build
        uses: ConsenSys/github-actions/docs-build@60d442d6d385b414c8e00eb049a85f56f9fd7be7 # main
