---
name: Build

on:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build
        uses: ConsenSys/github-actions/docs-build@7256f3d39c7bb71ec4ca9fc6078991302d4c8650 # main
