---
name: Check file name case

on:
  pull_request:
    branches:
      - main

jobs:
  case:
    name: Check for case being inconsistent
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ["docs"]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Case check action
        uses: ConsenSys/github-actions/docs-case-check@0fd1cb88921d5907ff2e348c5aa759196a053380 # main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOC_DIR: ${{ matrix.folder }}
          SKIP_TEST: true
