---
name: Check for broken links

on:
  pull_request:
    branches:
      - main

jobs:

  linkCheck:
    name: Link Checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: LinkCheck
        uses: ConsenSys/github-actions/docs-link-check@main
        with:
          fail_level: any