---
name: Check for broken links

on:
  pull_request:
    branches:
      - main

jobs:

  linkCheck:
    name: Link Checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: LinkCheck
        uses: ConsenSys/github-actions/docs-link-check@60d442d6d385b414c8e00eb049a85f56f9fd7be7 # main
        with:
          CONFIG_FILE: .linkspector.yml
