---
name: Check for lint/build errors

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code Base, Spelling, Link Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Lint
        uses: ConsenSys/docs-gha/lint@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linkCheck:
    name: Link Checking
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file-extensions: [".md", ".mdx"]
    steps:
      - uses: actions/checkout@v3
      - name: LinkCheck
        uses: ConsenSys/docs-gha/linkcheck@main
        with:
          FILE_EXTENSION: ${{ matrix.file-extensions }}
