---
name: Build and deploy to GitHub Pages

on:
  workflow_dispatch:
  workflow_call:

jobs:
  pages-deploy:
    name: Deploy to GitHub Pages
    runs-on: [self-hosted, linux, X64, large]
    # the enviroment to deploy to / use secrets from
    environment: no-secret
    # modify the default permissions of the GITHUB_TOKEN, so as to only allow least priveleges
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        uses: ConsenSys/docs-gha/pages-deploy@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
