---
name: Check for spelling with vale

on:
  pull_request:
    branches:
      - main

jobs:
  vale:
    name: Spelling
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Vale
        uses: Consensys/docs-gha/spelling@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILEPATHS: "docs"

